language: node_js

node_js:
  - "14.15"
sudo: required

before_script:
  - npm install -g @angular/cli
  
script:
  - npm run test-headless
  - ng build --base-href https://github.com/hvchan16/weather_app.git
